apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle.fullname" . }}-db
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
type: Opaque
stringData:
  MOODLE_DB_PASSWORD: {{ .Values.db.password | quote }}
