apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-efs-pv-staging
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "${EFS_ID}::${EFS_AP_STAGING_ID}"
