apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-efs-pvc
  namespace: moodle-staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
