apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: ndcuongdevops/moodle-lms:v1.0.6
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "400m"
            memory: "800Mi"
          limits:
            cpu: "1200m"
            memory: "1800Mi"
        env:
        - name: MOODLE_DB_HOST
          value: "REPLACE_WITH_DO_DB_HOST"
        - name: MOODLE_DB_NAME
          value: "moodle"
        - name: MOODLE_DB_USER
          value: "moodleuser"
        - name: MOODLE_DB_PASSWORD
          value: "REPLACE_WITH_DB_PASSWORD"
        volumeMounts:
        - name: moodle-data-volume
          mountPath: /var/www/moodledata
      volumes:
      - name: moodle-data-volume
        persistentVolumeClaim:
          claimName: moodle-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: DO_LOADBALANCER_NAME_PLACEHOLDER
    external-dns.alpha.kubernetes.io/hostname: EXTERNAL_DNS_HOSTNAME_PLACEHOLDER
spec:
  selector:
    app: moodle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
