apiVersion: v1
kind: Service
metadata:
  name: moodle-service
  namespace: moodle-production
spec:
  selector:
    app: moodle
    env: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
